### ISSUE TITLE
Create function to remove path prefix

### ISSUE THREAD

**Issue by skleinjung** [twin-digital/coco-toolbox#48]
We need a function to remove the leading slash from a path string if it has one. No unit tests are needed.

**Comment by coco-b0t** [comment]
#### Issue Status: **canceled**



#### Recent Activity

None

**Comment by coco-b0t** [comment]
This ticket is not sufficiently detailed. We need more information about what path prefix is being referred to. Is it a URL path prefix or a file path prefix? Also, we need to know what the expected behavior of the function is when removing the prefix. Does it remove the entire prefix or just a portion of it? Additionally, we need to know what the function should return if the prefix is not found in the string. Please provide more details so we can proceed with implementing this function.

**Comment by skleinjung** [comment]
try now

**Comment by coco-b0t** [comment]
I encountered an error while providing feedback: Unexpected token W in JSON at position 50

**Comment by skleinjung** [comment]
please use the required format only

**Comment by coco-b0t** [comment]
This ticket is sufficiently detailed. However, we need to clarify what type of path the function will be handling. Is it a file path or a URL path? Additionally, we need to know what the expected behavior of the function is when removing the prefix. Does it remove the entire prefix or just a portion of it? Finally, we need to know what the function should return if the prefix is not found in the string.
